server:
  port: 8082

spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.exemplo-spring
      routing-key:
        producer: rk.producer.exemplo-spring
      dead-letter:
        producer: dl.producer.exemplo-spring
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: rabbitmq
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgre
